Heart-and-Kidney-disease-prediction-Django-master/accounts/urls.py
from django.conf.urls import url
from . import views
app_name = 'accounts'
urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileDetailView.as_view(), name='profile'),
#url(r'^profile/(?P<pk>\d+)/edit/$', views.profile_update, name='edit_profile'),
]

Heart-and-Kidney-disease-prediction-Django-master/heart_disease_prediction/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

from accounts import views
from heart_disease_prediction import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.user_login,name='user_login'),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^predict/',include('predict_risk.urls')),
    url(r'^predict_1/',include('predict_risk_1.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Heart-and-Kidney-disease-prediction-Django-master/predict_risk_1/urls.py
from django.conf.urls import url
from . import views
app_name='predict_1'
urlpatterns=[
url(r'^(?P<pk>\d+)$',views.PredictRisk_1,name='predict_1')
]

Heart-and-Kidney-disease-prediction-Django-master/predict_risk_1/models.py
from django.db import models
from accounts.models import UserProfileInfo
from django.utils import timezone
from django.urls import reverse
# Create your models here.
sg_choices=((1.01,'1.01'),(1.02,'1.02'),(1.015,'1.015'),(1.025,'1.025'))
al_choices=((0,'0.0'),(1,'1.0'),(2,'2.0'),(3,'3.0'),(4,'4.0'))
su_choices=((0,'0.0'),(1,'1.0'),(2,'2.0'),(3,'3.0'),(4,'4.0'))
rbc_choices=((1,'normal'),(0,'abnormal'))
pc_choices=((1,'normal'),(0,'abnormal'))
pcc_choices=((1,'present'),(0,'notpresent'))
ba_choices=((1,'present'),(0,'notpresent'))
htn_choices=((1,'Yes'),(0,'No'))
dm_choices=((1,'Yes'),(0,'No'))
cad_choices=((1,'Yes'),(0,'No'))
appet_choices=((1,'good'),(0,'poor'))
pe_choices=((1,'Yes'),(0,'No'))
ane_choices=((1,'Yes'),(0,'No'))
classification_choices=((1,'ckd'),(0,'nockd'))




class Predictions_1(models.Model):
    profile = models.ForeignKey(UserProfileInfo, on_delete=models.CASCADE, related_name='predict_1')
    age = models.IntegerField(default=33)
    bp=models.IntegerField(default=80)
    sg=models.FloatField(choices=sg_choices,default=1.01)
    al=models.IntegerField(choices=al_choices,default=0)
    su=models.IntegerField(choices=su_choices,default=0)
    rbc=models.IntegerField(choices=rbc_choices,default=1)
    pc=models.IntegerField(choices=pc_choices,default=1)
    pcc=models.IntegerField(choices=pcc_choices,default=0)
    ba=models.IntegerField(choices=ba_choices,default=0)
    bgr=models.FloatField(default=89)
    bu=models.IntegerField(default=19)
    sc=models.FloatField(default=1)
    sod=models.FloatField(default=144)
    pot=models.FloatField(default=5)
    hemo=models.FloatField(default=15)
    pcv=models.IntegerField(default=40)
    wc=models.IntegerField(default=10300)
    rc=models.FloatField(default=5)
    htn=models.IntegerField(choices=htn_choices,default=0)
    dm=models.IntegerField(choices=dm_choices,default=0)
    cad=models.IntegerField(choices=cad_choices,default=0)
    appet=models.IntegerField(choices=appet_choices,default=1)
    pe=models.IntegerField(choices=pe_choices,default=0)
    ane=models.IntegerField(choices=ane_choices,default=0)



    predicted_on = models.DateTimeField(default=timezone.now)
    classification=models.IntegerField(choices=classification_choices,default=1)

    def get_absolute_url(self):
        return reverse('predict_1:predict_1', kwargs={'pk': self.profile.pk})

Heart-and-Kidney-disease-prediction-Django-master/predict_risk_1/forms.py
from django import forms
from predict_risk_1.models import Predictions_1

class Predict_Form_1(forms.ModelForm):
    class Meta:
        model = Predictions_1
        fields = ('age','bp','sg','al','su','rbc','pc','pcc',
        'ba','bgr','bu','sc','sod','pot','hemo','pcv','wc','rc','htn','dm','cad','appet','pe','ane')
        widgets = {
                   'age': forms.TextInput(attrs={'class': 'form-control'}),
                   'bp':forms.TextInput(attrs={'class': 'form-control'}),
               'sg':forms.Select(attrs={'class': 'form-control'}),
               'al':forms.Select(attrs={'class': 'form-control'}),
               'su':forms.Select(attrs={'class': 'form-control'}),
               'rbc':forms.Select(attrs={'class': 'form-control'}),
               'pc':forms.Select(attrs={'class': 'form-control'}),
               'pcc':forms.Select(attrs={'class': 'form-control'}),
               'ba':forms.Select(attrs={'class': 'form-control'}),
               'bgr':forms.TextInput(attrs={'class': 'form-control'}),
               'bu':forms.TextInput(attrs={'class': 'form-control'}),
               'sc':forms.TextInput(attrs={'class': 'form-control'}),
               'sod':forms.TextInput(attrs={'class': 'form-control'}),
               'pot':forms.TextInput(attrs={'class': 'form-control'}),
                'hemo':forms.TextInput(attrs={'class': 'form-control'}),
                'pcv':forms.TextInput(attrs={'class': 'form-control'}),
                'wc':forms.TextInput(attrs={'class': 'form-control'}),
                 'rc':forms.TextInput(attrs={'class': 'form-control'}),
                'htn':forms.Select(attrs={'class': 'form-control'}),
                'dm':forms.Select(attrs={'class': 'form-control'}),
                'cad':forms.Select(attrs={'class': 'form-control'}),
               'appet':forms.Select(attrs={'class': 'form-control'}),
               'pe':forms.Select(attrs={'class': 'form-control'}),
               'ane':forms.Select(attrs={'class': 'form-control'}),
              }

Heart-and-Kidney-disease-prediction-Django-master/predict_risk_1/views.py
import csv,io
from django.shortcuts import render
from .forms import Predict_Form_1
from predict_risk_1.data_provider import *
from accounts.models import UserProfileInfo
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required,permission_required
from django.urls import reverse
from django.contrib import messages


@login_required(login_url='/')
def PredictRisk_1(request,pk):
    predicted = False
    predictions={}
    if request.session.has_key('user_id'):
        u_id = request.session['user_id']

    if request.method == 'POST':
        form = Predict_Form_1(request.POST)
        print(form)
        print()
        print(request.POST)
        profile = get_object_or_404(UserProfileInfo, pk=pk)


        print("-------Enter into post-------")
        print(form.is_valid())
        if form.is_valid():

            print("----------Enter into valid---------")

            features = [[ form.cleaned_data['age'], form.cleaned_data['bp'], form.cleaned_data['sg'], form.cleaned_data['al'], form.cleaned_data['su'],
            form.cleaned_data['rbc'], form.cleaned_data['pc'], form.cleaned_data['pcc'], form.cleaned_data['ba'],
            form.cleaned_data['bgr'], form.cleaned_data['bu'], form.cleaned_data['sc'], form.cleaned_data['sod'], form.cleaned_data['pot'], form.cleaned_data['hemo'],
                          form.cleaned_data['pcv'], form.cleaned_data['wc'], form.cleaned_data['rc'], form.cleaned_data['htn'], form.cleaned_data['dm'],
                          form.cleaned_data['cad'], form.cleaned_data['appet'], form.cleaned_data['pe'], form.cleaned_data['ane']]]

            features1=features
            features2=features
            features3=features
            features4=features
            features5=features
            features6=features
            standard_scalar = GetStandardScalarForD()
            features1 = standard_scalar.transform(features1)

            standard_scalar = GetStandardScalarForL()
            features2 = standard_scalar.transform(features2)

            standard_scalar = GetStandardScalarForN()
            features3 = standard_scalar.transform(features3)

            standard_scalar = GetStandardScalarForS()
            features4 = standard_scalar.transform(features4)

            standard_scalar = GetStandardScalarForNN()
            features5 = standard_scalar.transform(features5)

            standard_scalar = GetStandardScalarForKNN()
            features6 = standard_scalar.transform(features6)


            SVCClassifier,LogisticRegressionClassifier,NaiveBayesClassifier,DecisionTreeClassifier,NNClassifier,KNNClassifier=GetAllClassifiersForKidney()

            print(features)
            predictions = {'SVC': str(SVCClassifier.predict(features1)[0]),
            'LogisticRegression': str(LogisticRegressionClassifier.predict(features2)[0]),
             'NaiveBayes': str(NaiveBayesClassifier.predict(features3)[0]),
             'DecisionTree': str(DecisionTreeClassifier.predict(features4)[0]),
              'NeuralNetwork': str(NNClassifier.predict(features5)[0]),
               'KNN': str(KNNClassifier.predict(features6)[0]),
              }
            pred = form.save(commit=False)

            print(predictions)

            l=[predictions['SVC'],predictions['LogisticRegression'],predictions['NaiveBayes'],predictions['DecisionTree'],predictions['NeuralNetwork'],predictions['KNN']]
            count=l.count('1')

            result=False

            if count>=3:
                result=True
                pred.classification=1
            else:
                pred.classification=0

            pred.profile = profile

            pred.save()
            predicted = True

            colors={}

            if predictions['SVC']=='0':
                colors['SVC']="table-success"
            elif predictions['SVC']=='1':
                colors['SVC']="table-danger"

            if predictions['LogisticRegression']=='0':
                colors['LR']="table-success"
            else:
                colors['LR']="table-danger"

            if predictions['NaiveBayes']=='0':
                colors['NB']="table-success"
            else:
                colors['NB']="table-danger"

            if predictions['DecisionTree']=='0':
                colors['DT']="table-success"
            else:
                colors['DT']="table-danger"

            if predictions['NeuralNetwork']=='0':
                colors['NN']="table-success"
            else:
                colors['NN']="table-danger"

            if predictions['KNN']=='0':
                colors['KNN']="table-success"
            else:
                colors['KNN']="table-danger"

    if predicted:
        return render(request, 'predict_1.html',
                      {'form': form,'predicted': predicted,'user_id':u_id,'predictions':predictions,'result':result,'colors':colors})

    else:
        form = Predict_Form_1()

        return render(request, 'predict_1.html',
                      {'form': form,'predicted': predicted,'user_id':u_id,'predictions':predictions})

Heart-and-Kidney-disease-prediction-Django-master/predict_risk_1/templates/predict_1.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
<title>Medical Emergency Form a Responsive Widget Template :: w3layouts</title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<link href="{% static 'css/style2.css' %}" rel="stylesheet" />

<link href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
<link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />
<link href="{% static 'css/medium-editor.min.css' %}" rel="stylesheet">
<!--//fonts-->
</head>
<body style="background-image: url('{% static 'images/2.jpg' %}')">
<!--background-->
<nav class="navbar navbar-expand-lg navbar-transparent" >
        <div class="container">
            <div class="collapse navbar-collapse justify-content-end" id="navigation" >
                <ul class="navbar-nav nav-tabs">

                    <li class="nav-item"><a href="{% url 'accounts:profile' pk=user_id %}" class="btn btn-neutral">Profile</a></li>
                      <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="btn btn-neutral">Logout</a></li>

                </ul>
            </div>
        </div>
    </nav>
<h1>Predict your Chronic Kidney disease</h1>
    <div class="bg-agile">
	<div class="book-appointment">
	<h2>Medical Information</h2>

  {% if predicted %}
<div class="card" role="alert">
<div class="header-main">
{% if result %}
<h4 class="table-danger text-center">You have a risk of kidney disease</h4>
{% else %}
<h4 class="table-success  text-center">You do not have a risk of kidney disease</h4>
{% endif %}
</div>
<div class="card-body">
      <div class="table-responsive justify-content-center">
                       <table class="table">
                           <thead>
                               <tr>
                                   <th>Algorithm</th>
                                   <th>Risk of Kidney Disease</th>
                               </tr>
                           </thead>
                           <tbody>
                               <tr class="{{colors.LR}}">
                                   <td>Logistic Regression</td>
                                   <td>{{predictions.LogisticRegression}}</td>
                               </tr>
                               <tr class={{colors.SVC}}>
                                   <td>Support Vector Classifier</td>
                                   <td>{{predictions.SVC}}</td>
                               </tr>
                               <tr class={{colors.NB}}>
                                   <td>Naive Bayes</td>
                                   <td>{{predictions.NaiveBayes}}</td>
                               </tr>
                               <tr class={{colors.DT}}>
                                   <td>Decision Tree</td>
                                   <td>{{predictions.DecisionTree}}</td>
                               </tr>

                               </tr>
                               <tr class={{colors.NN}}>
                                   <td>Neural Network</td>
                                   <td>{{predictions.NeuralNetwork}}</td>
                               </tr>

                               </tr>
                               <tr class={{colors.KNN}}>
                                   <td>KNN</td>
                                   <td>{{predictions.KNN}}</td>
                               </tr>
                           </tbody>

                       </table>
                   </div>
               </div>
             </div>

  {% endif %}

			<form method="post">
        {% csrf_token %}
        <div class="left-agileits-w3layouts same">
          <div class="gaps">
            <p>Age<p>
            {{form.age}}
          </div>

					<div class="gaps">
						<p>Blood Pressure</p>
							{{form.bp}}
					</div>

          <div class="gaps">
            <p>Specific Gravity</p>
              {{form.sg}}
          </div>

					<div class="gaps">
						<p>Albumin</p>
							{{form.al}}
					</div>

					<div class="gaps">
						<p>Sugar</p>
							{{form.su}}
					</div>

					<div class="gaps">
						<p>Red Blood Cells</p>
						   {{form.rbc}}
					</div>

					<div class="gaps">
						<p>Puss Cells</p>
						{{form.pc}}
					</div>

					<div class="gaps">
						<p>Puss Cells Clumps</p>
						{{form.pcc}}
					</div>

					<div class="gaps">
						<p>Bacteria</p>
						{{form.ba}}
					</div>

					<div class="gaps">
						<p>Red Glucose Random</p>
						{{form.bgr}}
					</div>

               <div class="gaps">
						<p>Blood Urea </p>
				      {{form.bu}}
					</div>

             <div class="gaps">
            <p>Serum Creatinine</p>
              {{form.sc}}
          </div>

				</div>

				<div class="right-agileinfo same">





          <div class="gaps">
            <p>Sodium</p>
              {{form.sod}}
          </div>

           <div class="gaps">
            <p>Potassium</p>
              {{form.pot}}
          </div>

            <div class="gaps">
            <p>Haemoglobin</p>
              {{form.hemo}}
          </div>

              <div class="gaps">
            <p>Packed Cell Volume</p>
              {{form.pcv}}
          </div>


                    <div class="gaps">
                    <p>White Blood cell count</p>
                   {{form.wc}}
                   </div>

                     <div class="gaps">
                    <p>Red Blood cell count</p>
                   {{form.rc}}
                   </div>

                     <div class="gaps">
                    <p>Hypertension</p>
                   {{form.htn}}
                   </div>

                     <div class="gaps">
                    <p>Diabetes mellitus</p>
                   {{form.dm}}
                   </div>

                     <div class="gaps">
                    <p>Coronary Artery Disease</p>
                   {{form.cad}}
                   </div>

                     <div class="gaps">
                    <p>Appetite</p>
                   {{form.appet}}
                   </div>

                     <div class="gaps">
                    <p>Pedal Edema</p>
                   {{form.pe}}
                   </div>

                     <div class="gaps">
                    <p>Anemia</p>
                   {{form.ane}}
                   </div>

				</div>

				<div class="clear"></div>
				<input type="submit" value="Predict" class="btn btn-primary">
			</form>
		</div>
   </div>
   <!--copyright-->

		<!--//copyright-->
		<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
		<!-- Calendar -->
				<link rel="stylesheet" href="css/jquery-ui.css" />
				<script src="js/jquery-ui.js"></script>

			<!-- //Calendar -->

</body>
</html>